server:
  port: 8099

scheduled:
  task:
    cron: 0 0/5 * * * *
    enable: true
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    mongodb:
      database: ${MONGODB_DB}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: root
      password: password123

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
