server:
  port: 8099

scheduled:
  task:
    cron: 0/5 * * * * *
    enable: false
spring:
  data:
    mongodb:
      database: ${MONGODB_DB}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: root
      password: password123

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
